export const AI_ANALYSIS_TYPES = [
  'COMPANY_ANALYSIS',
  'OPPORTUNITY_CLASSIFICATION',
  'CONTENT_PREPARATION',
  'PAGE_ANALYSIS',
  'LINK_INSERT_PREPARATION',
  'ANCHOR_RECOMMENDATION',
  'OUTREACH_MESSAGE',
  'NEGOTIATION_ANALYSIS',
  'DONOR_QUALITY_ESTIMATES',
  'DONOR_RISK',
] as const;

export type AIAnalysisType = (typeof AI_ANALYSIS_TYPES)[number];

export const AI_ANALYSIS_VALIDATION_STATUSES = ['VALID', 'INVALID'] as const;

export type AIAnalysisValidationStatus = (typeof AI_ANALYSIS_VALIDATION_STATUSES)[number];
