export const PLACEMENT_TYPES = [
  'BACKLINK',
  'BRAND_MENTION',
  'BUSINESS_PROFILE',
  'DIRECTORY_LISTING',
  'PRODUCT_LISTING',
  'EDITORIAL_PUBLICATION',
  'SOCIAL_PROFILE',
  'REFERRAL_TRAFFIC',
  'LINK_INSERT',
  'GUEST_POST',
  'RESOURCE_PAGE',
  'PARTNER_PAGE',
] as const;

export type PlacementType = (typeof PLACEMENT_TYPES)[number];
